Repository getsentry/sentry-laravel, pull requests merged in 2022-10, with the labels that each got.

#578 Prepare 2.14.0
  CHANGELOG.md
Labels: Type: Documentation

#572 feat: Add support for Dynamic Sampling
  composer.json
  src/Sentry/Laravel/Console/TestCommand.php
  src/Sentry/Laravel/EventHandler.php
  src/Sentry/Laravel/Integration.php
  src/Sentry/Laravel/Tracing/EventHandler.php
  src/Sentry/Laravel/Tracing/Integrations/LighthouseIntegration.php
  src/Sentry/Laravel/Tracing/Middleware.php
Labels: Type: Improvement, Status: In Progress

#582 Fix not setting correct SDK ID/version when running test command
  CHANGELOG.md
  src/Sentry/Laravel/Console/TestCommand.php
Labels: Type: Bug

#579 Drop Laravel Lumen support
  CHANGELOG.md
  README.md
  composer.json
  src/Sentry/Laravel/Integration.php
  src/Sentry/Laravel/ServiceProvider.php
  src/Sentry/Laravel/Tracing/Middleware.php
  src/Sentry/Laravel/Tracing/ServiceProvider.php
  test/Sentry/IntegrationTest.php
Labels: Status: In Progress, Type: Deprecation

#581 Drop Laravel 5.x support
  .github/workflows/ci.yaml
  CHANGELOG.md
  README.md
  composer.json
  src/Sentry/Laravel/Console/PublishCommand.php
  src/Sentry/Laravel/Console/TestCommand.php
  src/Sentry/Laravel/EventHandler.php
  src/Sentry/Laravel/Http/SetRequestMiddleware.php
  src/Sentry/Laravel/Integration.php
  src/Sentry/Laravel/Tracing/EventHandler.php
  test/Sentry/CommandInfoInBreadcrumbsTest.php
  test/Sentry/IntegrationTest.php
  test/Sentry/Laravel/LogChannelTest.php
  test/Sentry/LaravelLogsInBreadcrumbsTest.php
  test/Sentry/SentryLaravelTestCase.php
  test/Sentry/SqlBindingsInBreadcrumbsTest.php
  test/Sentry/SqlBindingsInBreadcrumbsWithOldConfigKeyDisabledTest.php
  test/Sentry/SqlBindingsInBreadcrumbsWithOldConfigKeyEnabledTest.php
  test/Sentry/SqlQueriesInBreadcrumbsTest.php
Labels: Status: In Progress, Type: Deprecation

#584 Revert "feat: Add support for Dynamic Sampling (#572)"
  composer.json
  src/Sentry/Laravel/Console/TestCommand.php
  src/Sentry/Laravel/EventHandler.php
  src/Sentry/Laravel/Integration.php
  src/Sentry/Laravel/Tracing/EventHandler.php
  src/Sentry/Laravel/Tracing/Integrations/LighthouseIntegration.php
  src/Sentry/Laravel/Tracing/Middleware.php
Labels: Status: In Progress

#585 Add tracing span for Laravel HTTP client requests
  src/Sentry/Laravel/Tracing/EventHandler.php
Labels: Type: Improvement, Status: In Progress

#580 Improve tracing
  CHANGELOG.md
  config/sentry.php
  src/Sentry/Laravel/Integration.php
  src/Sentry/Laravel/ServiceProvider.php
  src/Sentry/Laravel/Tracing/EventHandler.php
  src/Sentry/Laravel/Tracing/Middleware.php
  test/Sentry/IntegrationTest.php
Labels: Type: Improvement, Status: In Progress, Type: Deprecation

#589 Fix command input handling
  CHANGELOG.md
  src/Sentry/Laravel/EventHandler.php
  test/Sentry/CommandInfoInBreadcrumbsTest.php
Labels: Type: Bug, Status: In Progress

#590 docs: Add 3.0.0 changelog
  CHANGELOG.md
Labels: Type: Documentation

#594 Add `db.transaction` span
  CHANGELOG.md
  src/Sentry/Laravel/Tracing/EventHandler.php
Labels: Type: Feature

#593 Add `http.route` span
  CHANGELOG.md
  src/Sentry/Laravel/Tracing/Routing/TracingCallableDispatcherTracing.php
  src/Sentry/Laravel/Tracing/Routing/TracingControllerDispatcherTracing.php
  src/Sentry/Laravel/Tracing/Routing/TracingRoutingDispatcher.php
  src/Sentry/Laravel/Tracing/ServiceProvider.php
Labels: Type: Feature

#592 Cleanup event handlers
  CHANGELOG.md
  src/Sentry/Laravel/EventHandler.php
  src/Sentry/Laravel/Integration.php
  src/Sentry/Laravel/ServiceProvider.php
  src/Sentry/Laravel/Tracing/EventHandler.php
  src/Sentry/Laravel/Tracing/Integrations/LighthouseIntegration.php
  src/Sentry/Laravel/Tracing/Routing/TracingCallableDispatcherTracing.php
  src/Sentry/Laravel/Tracing/Routing/TracingControllerDispatcherTracing.php
  src/Sentry/Laravel/Tracing/Routing/TracingRoutingDispatcher.php
  src/Sentry/Laravel/Tracing/ServiceProvider.php
  src/Sentry/Laravel/Tracing/ViewEngineDecorator.php
  test/Sentry/Tracing/EventHandlerTest.php
Labels: Type: Improvement

#597 docs: Restructure the 3.0.0 changelog
  CHANGELOG.md
Labels: Type: Documentation

#599 Update branch aliasses with new versions
  composer.json
Labels: Type: Improvement, Status: In Progress

#602 meta: Update README.md
  README.md
Labels: Type: Documentation

#600 Always start performance tracing
  CHANGELOG.md
  composer.json
  src/Sentry/Laravel/EventHandler.php
  src/Sentry/Laravel/ServiceProvider.php
  src/Sentry/Laravel/Tracing/EventHandler.php
  src/Sentry/Laravel/Tracing/Middleware.php
  src/Sentry/Laravel/Tracing/Routing/TracingRoutingDispatcher.php
  src/Sentry/Laravel/Tracing/ServiceProvider.php
Labels: Type: Bug, Status: In Progress

#603 Support using SENTRY_RELEASE environment variable
  CHANGELOG.md
  config/sentry.php
Labels: Type: Improvement, Status: In Progress
