Repository getsentry/sentry-laravel, pull requests merged in 2022-09, with the labels that each got.

#573 fix: Status code not populated on transaction if response did not inherit from the Laravel Response class
  CHANGELOG.md
  src/Sentry/Laravel/Tracing/Middleware.php
Labels: Type: Bug, Status: In Progress

#568 fix: Fix not listening to queue events because `QueueManager` is registered as `queue` in the container and not by it's class name
  CHANGELOG.md
  src/Sentry/Laravel/Tracing/ServiceProvider.php
Labels: Type: Bug, Status: In Progress

#575 fix: Broken `SetRequestMiddleware` on Laravel < 6.0
  CHANGELOG.md
  composer.json
  src/Sentry/Laravel/Http/LaravelRequestFetcher.php
  src/Sentry/Laravel/Http/SetRequestMiddleware.php
  src/Sentry/Laravel/ServiceProvider.php
Labels: Type: Bug, Status: In Progress

#574 ref: Align Span Operations with new spec
  CHANGELOG.md
  src/Sentry/Laravel/Tracing/Middleware.php
  src/Sentry/Laravel/Tracing/ViewEngineDecorator.php
Labels: Type: Improvement

#576 Upgrade php-cs-fixer dependency
  .github/workflows/cs.yaml
  .gitignore
  .php-cs-fixer.php
  composer.json
Labels: Type: Improvement, Status: In Progress
