Repository getsentry/sentry-laravel, pull requests merged in 2022-11, with the labels that each got.

#608 Introduce `captureUnhandledException`
  CHANGELOG.md
  src/Sentry/Laravel/Integration.php
Labels: Type: Improvement, Status: In Progress

#610 Prepare 3.1.0
  CHANGELOG.md
Labels: Type: Documentation

#611 Fix missing scope information on unhandled exceptions
  CHANGELOG.md
  src/Sentry/Laravel/Integration.php
Labels: Type: Bug

#617 Make an educated guess if the exception actually was handled
  CHANGELOG.md
  composer.json
  src/Sentry/Laravel/Integration.php
  test/Sentry/IntegrationTest.php
  test/Sentry/TestCase.php
  test/Sentry/TestCaseExceptionHandler.php
Labels: Type: Bug

#616 Set `traces_sample_rate` to `null` by default
  CHANGELOG.md
  composer.json
  config/sentry.php
Labels: Type: Feature

#618 Update CHANGELOG.md
  CHANGELOG.md
Labels: Type: Documentation

#620 Prepare 3.1.2
  CHANGELOG.md
Labels: Type: Documentation

#621 Update README.md
  README.md
Labels: Type: Documentation
