Repository getsentry/sentry-laravel, pull requests merged in 2023-11, with the labels that each got.

#791 Add permissions to GitHub actions
  .github/workflows/ci.yaml
  .github/workflows/cs.yaml
  .github/workflows/publish-release.yaml
  .github/workflows/static-analysis.yaml
Labels: Type: Improvement

#793 Bump PHP SDK to 4.0
  composer.json
  src/Sentry/Laravel/ServiceProvider.php
  test/Sentry/ClientBuilderDecoratorTest.php
  test/Sentry/ServiceProviderTest.php
  test/Sentry/ServiceProviderWithCustomAliasTest.php
  test/Sentry/TestCase.php
Labels: Type: Improvement

#794 Add support for PHPUnit 10
  composer.json
  test/Sentry/Integration/ExceptionContextIntegrationTest.php
  test/Sentry/LogChannelTest.php
Labels: Type: Improvement

#772 Improve how we signal that a route was matched
  src/Sentry/Laravel/EventHandler.php
  src/Sentry/Laravel/Features/FolioPackageIntegration.php
  src/Sentry/Laravel/Tracing/Middleware.php
  test/Sentry/ClientBuilderDecoratorTest.php
  test/Sentry/EventHandler/ConsoleEventsTest.php
  test/Sentry/EventHandler/DatabaseEventsTest.php
  test/Sentry/EventHandler/LogEventsTest.php
  test/Sentry/EventHandler/QueueEventsTest.php
  test/Sentry/Features/CacheIntegrationTest.php
  test/Sentry/Features/ConsoleIntegrationTest.php
  test/Sentry/Features/FolioPackageIntegrationTest.php
  test/Sentry/Features/HttpClientIntegrationTest.php
  test/Sentry/Features/LogIntegrationTest.php
  test/Sentry/Features/RouteIntegrationTest.php
  test/Sentry/Features/StorageIntegrationTest.php
  test/Sentry/Integration/ExceptionContextIntegrationTest.php
  test/Sentry/IntegrationTest.php
  test/Sentry/Laravel/LaravelIntegrationsOptionTest.php
  test/Sentry/LogChannelTest.php
  test/Sentry/ServiceProviderWithEnvironmentFromConfigTest.php
  test/Sentry/TestCase.php
Labels: Type: Improvement

#797 Refactor HTTP client integration feature
  composer.json
  src/Sentry/Laravel/EventHandler.php
  src/Sentry/Laravel/Features/Concerns/TracksPushedScopesAndSpans.php
  src/Sentry/Laravel/Features/HttpClientIntegration.php
  src/Sentry/Laravel/Features/QueueIntegration.php
  src/Sentry/Laravel/ServiceProvider.php
  src/Sentry/Laravel/Tracing/EventHandler.php
  src/Sentry/Laravel/Util/WorksWithUris.php
  test/Sentry/Features/HttpClientIntegrationTest.php
Labels: Type: Improvement

#798 Added support for Livewire 3
  .github/workflows/ci.yaml
  composer.json
  phpstan-baseline.neon
  src/Sentry/Laravel/Features/LivewirePackageIntegration.php
Labels: Type: Improvement

#796 Prepare 4.0
  CHANGELOG.md
Labels: Type: Documentation

#800 4.x
  .github/workflows/ci.yaml
  .github/workflows/cs.yaml
  .github/workflows/publish-release.yaml
  .github/workflows/static-analysis.yaml
  CHANGELOG.md
  codecov.yml
  composer.json
  phpstan-baseline.neon
  src/Sentry/Laravel/EventHandler.php
  src/Sentry/Laravel/Features/Concerns/TracksPushedScopesAndSpans.php
  src/Sentry/Laravel/Features/FolioPackageIntegration.php
  src/Sentry/Laravel/Features/HttpClientIntegration.php
  src/Sentry/Laravel/Features/LivewirePackageIntegration.php
  src/Sentry/Laravel/Features/QueueIntegration.php
  src/Sentry/Laravel/ServiceProvider.php
  src/Sentry/Laravel/Tracing/EventHandler.php
  src/Sentry/Laravel/Tracing/Middleware.php
  src/Sentry/Laravel/Util/WorksWithUris.php
  test/Sentry/ClientBuilderDecoratorTest.php
  test/Sentry/EventHandler/ConsoleEventsTest.php
  test/Sentry/EventHandler/DatabaseEventsTest.php
  test/Sentry/EventHandler/LogEventsTest.php
  test/Sentry/EventHandler/QueueEventsTest.php
  test/Sentry/Features/CacheIntegrationTest.php
  test/Sentry/Features/ConsoleIntegrationTest.php
  test/Sentry/Features/FolioPackageIntegrationTest.php
  test/Sentry/Features/HttpClientIntegrationTest.php
  test/Sentry/Features/LogIntegrationTest.php
  test/Sentry/Features/RouteIntegrationTest.php
  test/Sentry/Features/StorageIntegrationTest.php
  test/Sentry/Integration/ExceptionContextIntegrationTest.php
  test/Sentry/IntegrationTest.php
  test/Sentry/Laravel/LaravelIntegrationsOptionTest.php
  test/Sentry/LogChannelTest.php
  test/Sentry/ServiceProviderTest.php
  test/Sentry/ServiceProviderWithCustomAliasTest.php
  test/Sentry/ServiceProviderWithEnvironmentFromConfigTest.php
  test/Sentry/TestCase.php
Labels: Type: Improvement, Type: Feature

#803 Unify backtrace origin
  src/Sentry/Laravel/Tracing/EventHandler.php
Labels: Type: Improvement

#802 Add `ignore_exceptions` & `ignore_transactions` to the default config
  config/sentry.php
Labels: Type: Improvement

#804 Adding bindings to SQL spans in tracing
  config/sentry.php
  src/Sentry/Laravel/Tracing/EventHandler.php
  test/Sentry/Features/DatabaseIntegrationTest.php
  test/Sentry/Tracing/EventHandlerTest.php
Labels: Type: Feature

#809 Prepare 4.1.0
  CHANGELOG.md
Labels: Type: Documentation
