Repository getsentry/sentry-laravel, pull requests merged in 2023-07, with the labels that each got.

#724 Fix not accounting for Lumen application instance in tracing middleware
  src/Sentry/Laravel/Tracing/Middleware.php
  src/Sentry/Laravel/Tracing/ServiceProvider.php
Labels: Type: Bug, Status: In Progress

#725 Prepare 3.6.1
  CHANGELOG.md
Labels: Type: Documentation

#719 Tracing without Performance
  composer.json
  src/Sentry/Laravel/Features/QueueIntegration.php
  src/Sentry/Laravel/Integration.php
  src/Sentry/Laravel/Tracing/Middleware.php
Labels: Status: In Progress, Type: Feature

#720 GraphQL and HTTP client improvements
  src/Sentry/Laravel/EventHandler.php
  src/Sentry/Laravel/Tracing/Integrations/LighthouseIntegration.php
Labels: Type: Feature

#727 Make it configurable if the performance traces continues after the response has been sent
  config/sentry.php
  src/Sentry/Laravel/Tracing/Middleware.php
  src/Sentry/Laravel/Tracing/ServiceProvider.php
Labels: Type: Improvement

#732 Less sensitive data by default
  config/sentry.php
  src/Sentry/Laravel/Http/LaravelRequestFetcher.php
Labels: Type: Improvement

#726 Add tracing for storage access
  composer.json
  config/sentry.php
  src/Sentry/Laravel/EventHandler.php
  src/Sentry/Laravel/Features/Storage/Integration.php
  src/Sentry/Laravel/Features/Storage/SentryCloudFilesystem.php
  src/Sentry/Laravel/Features/Storage/SentryFilesystem.php
  src/Sentry/Laravel/ServiceProvider.php
  src/Sentry/Laravel/Tracing/EventHandler.php
  src/Sentry/Laravel/Tracing/ViewEngineDecorator.php
  src/Sentry/Laravel/Util/Filesize.php
  test/Sentry/Features/CacheIntegrationTest.php
  test/Sentry/Features/StorageIntegrationTest.php
  test/Sentry/LogChannelTest.php
  test/Sentry/TestCaseExceptionHandler.php
Labels: Type: Feature

#735 Update default config file with `env` for everything and added docs
  config/sentry.php
Labels: Type: Improvement

#743 Handle exceptions raised while resolving the request
  src/Sentry/Laravel/Http/SetRequestMiddleware.php
Labels: Type: Bug

#744 Prepare 3.7.0
  CHANGELOG.md
Labels: Type: Documentation
