Repository getsentry/sentry-laravel, pull requests merged in 2023-05, with the labels that each got.

#678 Add helper to report lazy loading violations
  src/Sentry/Laravel/Features/Concerns/ResolvesEventOrigin.php
  src/Sentry/Laravel/Integration.php
Labels: Status: In Progress, Type: Feature

#686 Clean up setup and docs
  CONTRIBUTING.md
  Makefile
  README.md
  composer.json
  config/sentry.php
Labels: Type: Improvement, Status: In Progress

#685 Reintroduce Lumen support
  README.md
  composer.json
  src/Sentry/Laravel/Integration.php
  src/Sentry/Laravel/ServiceProvider.php
  src/Sentry/Laravel/Tracing/ServiceProvider.php
  test/Sentry/IntegrationTest.php
Labels: Type: Improvement, Status: In Progress

#698 Allow setting up features in an inactive state
  src/Sentry/Laravel/Features/ConsoleIntegration.php
  src/Sentry/Laravel/Features/Feature.php
  src/Sentry/Laravel/ServiceProvider.php
Labels: Type: Bug

#705 fix: Make sentryMonitor macro chainable
  src/Sentry/Laravel/Features/ConsoleIntegration.php
Labels: Type: Bug

#706 Prepare 3.4.1
  CHANGELOG.md
Labels: Type: Documentation
