Repository getsentry/sentry-laravel, pull requests merged in 2023-10, with the labels that each got.

#780 Fix deprecation message for str_starts_with
  src/Sentry/Laravel/Tracing/Integrations/LighthouseIntegration.php
Labels: Type: Improvement

#781 Prepare 3.8.1
  CHANGELOG.md
Labels: Type: Documentation

#783 Fix `DateTimeZone` not properly converted to a string
  src/Sentry/Laravel/Features/ConsoleIntegration.php
  test/Sentry/Features/ConsoleIntegrationTest.php
Labels: Type: Bug

#784 Prepare 3.8.2
  CHANGELOG.md
Labels: Type: Documentation

#785 Run CI on PHP 8.3
  .github/workflows/ci.yaml
Labels: Type: Improvement
