Repository getsentry/sentry-laravel, pull requests merged in 2023-09, with the labels that each got.

#771 Always register the about command integration
  src/Sentry/Laravel/ServiceProvider.php
Labels: Type: Improvement

#738 Laravel Folio support
  .github/workflows/ci.yaml
  composer.json
  src/Sentry/Laravel/EventHandler.php
  src/Sentry/Laravel/Features/FolioPackageIntegration.php
  src/Sentry/Laravel/ServiceProvider.php
  test/Sentry/Features/DatabaseIntegrationTest.php
  test/Sentry/Features/FolioPackageIntegrationTest.php
  test/Sentry/Features/StorageIntegrationTest.php
  test/Sentry/TestCase.php
  test/stubs/folio/index.blade.php
  test/stubs/folio/post/[id].blade.php
  test/stubs/folio/posts/[...ids].blade.php
  test/stubs/folio/user/[.Sentry.Features.FolioPackageIntegrationUserModel].blade.php
Labels: Type: Feature

#770 Prepare 3.8.0
  CHANGELOG.md
Labels: Type: Documentation
