Repository getsentry/sentry-laravel, pull requests merged in 2023-03, with the labels that each got.

#647 feat: Install an JavaScript SDK during sentry:publish
  src/Sentry/Laravel/Console/PublishCommand.php
  stubs/sentry-javascript/angular.js
  stubs/sentry-javascript/browser.js
  stubs/sentry-javascript/react.js
  stubs/sentry-javascript/svelte.js
  stubs/sentry-javascript/vue.js
Labels: Status: In Progress, Type: Feature

#657 Add Livewire tracing integration
  config/sentry.php
  src/Sentry/Laravel/Features/Feature.php
  src/Sentry/Laravel/Features/LivewirePackageIntegration.php
  src/Sentry/Laravel/ServiceProvider.php
Labels: Status: In Progress, Type: Feature

#656 Cache performance spans & breadcrumbs
  config/sentry.php
  src/Sentry/Laravel/Features/CacheIntegration.php
  src/Sentry/Laravel/Features/Concerns/ResolvesEventOrigin.php
  src/Sentry/Laravel/Features/Feature.php
  src/Sentry/Laravel/ServiceProvider.php
  src/Sentry/Laravel/Tracing/EventHandler.php
  test/Sentry/Features/CacheIntegrationTest.php
  test/Sentry/TestCase.php
Labels: Status: In Progress, Type: Feature

#660 ref: Fix too many arguments
  src/Sentry/Laravel/Console/PublishCommand.php
  src/Sentry/Laravel/ServiceProvider.php
Labels: Type: Improvement, Status: In Progress

#659 feat: Add support for Scheduled Tasks monitoring
  composer.json
  src/Sentry/Laravel/Features/ConsoleIntegration.php
  src/Sentry/Laravel/ServiceProvider.php
Labels: Status: In Progress, Type: Feature

#661 Prepare 3.3.0
  CHANGELOG.md
Labels: Type: Documentation, Status: In Progress

#664 Fix scheduled commands running in background not reporting success/failure
  src/Sentry/Laravel/Features/ConsoleIntegration.php
Labels: Type: Bug, Status: In Progress

#665 Prepare 3.3.1
  CHANGELOG.md
Labels: Type: Documentation

#666 Update README.md
  README.md
Labels: Type: Documentation
