Repository getsentry/sentry-laravel, pull requests merged in 2024-04, with the labels that each got.

#877 Fix filesystem `assertExists`/`assertMissing` not handling array as path argument
  src/Sentry/Laravel/Features/Storage/FilesystemAdapterDecorator.php
  src/Sentry/Laravel/Features/Storage/FilesystemDecorator.php
  test/Sentry/Features/StorageIntegrationTest.php
Labels: Type: Bug

#852 Implement notifications tracing and breadcrumbs
  config/sentry.php
  src/Sentry/Laravel/Features/NotificationsIntegration.php
  src/Sentry/Laravel/ServiceProvider.php
  test/Sentry/Features/NotificationsIntegrationTest.php
  test/Sentry/TestCase.php
Labels: Type: Improvement

#880 Make it easier to enable the debug logger
  config/sentry.php
  src/Sentry/Laravel/ServiceProvider.php
  test/Sentry/Laravel/LaravelContainerConfigOptionsTest.php
  test/Sentry/Laravel/LaravelIntegrationsConfigOptionTest.php
Labels: Type: Improvement

#824 Add reporter for `Model::preventAccessingMissingAttributes()`
  src/Sentry/Laravel/Integration.php
Labels: Type: Feature

#886 Bump `sentry/sentry` to `^4.7`
  composer.json
Labels: Type: Bug

#883 LighthouseIntegration: Fix finding the operation definition node on the query
  phpstan-baseline.neon
  src/Sentry/Laravel/Tracing/Integrations/LighthouseIntegration.php
Labels: Type: Bug

#881 Limit cases where SQL origin is captured
  config/sentry.php
  src/Sentry/Laravel/Features/CacheIntegration.php
  src/Sentry/Laravel/Features/Concerns/ResolvesEventOrigin.php
  src/Sentry/Laravel/Integration.php
  src/Sentry/Laravel/Tracing/EventHandler.php
  test/Sentry/Features/DatabaseIntegrationTest.php
Labels: Type: Improvement

#887 Fix username not being a string resulting in exception
  src/Sentry/Laravel/EventHandler.php
  test/Sentry/EventHandler/AuthEventsTest.php
Labels: Type: Bug

#890 Fix discarded attribute violation reporter not accepting multiple property names
  src/Sentry/Laravel/Integration/ModelViolations/ModelViolationReporter.php
  test/Sentry/Integration/ModelViolationReportersTest.php
Labels: Type: Bug

#891 Prepare 4.5.1
  CHANGELOG.md
Labels: Type: Documentation
