Repository getsentry/sentry-laravel, pull requests merged in 2024-06, with the labels that each got.

#902 Add support for the Queue Module
  src/Sentry/Laravel/Features/QueueIntegration.php
Labels: Type: Feature

#900 Always register the console scheduling macro
  src/Sentry/Laravel/Features/ConsoleSchedulingIntegration.php
Labels: Type: Bug

#901 fix: Avoid manipulating config when resolving disks
  src/Sentry/Laravel/Features/Storage/Integration.php
  test/Sentry/Features/StorageIntegrationTest.php
Labels: Type: Improvement

#908 Prepare 4.6.0
  CHANGELOG.md
Labels: Type: Documentation

#910 Normalize the queue name
  src/Sentry/Laravel/Features/QueueIntegration.php
Labels: Type: Improvement

#911 Prepare 4.6.1
  CHANGELOG.md
Labels: Type: Documentation
