Repository getsentry/sentry-laravel, pull requests merged in 2024-01, with the labels that each got.

#820 Queue tracing bugfixes
  composer.json
  src/Sentry/Laravel/Features/Feature.php
  src/Sentry/Laravel/Features/HttpClientIntegration.php
  src/Sentry/Laravel/Features/QueueIntegration.php
  src/Sentry/Laravel/Tracing/EventHandler.php
  test/Sentry/Features/HttpClientIntegrationTest.php
  test/Sentry/Features/QueueIntegrationTest.php
Labels: Type: Bug

#822 Laravel Lumen performance traces not collected because route never matched
  phpstan-baseline.neon
  src/Sentry/Laravel/Tracing/Middleware.php
Labels: Type: Bug

#826 Fix unable to set callable for `integrations` option
  src/Sentry/Laravel/ServiceProvider.php
Labels: Type: Bug

#829 Allow newer version of PSR HTTP message bridge
  composer.json
  test/Sentry/Http/LaravelRequestFetcherTest.php
Labels: Type: Improvement

#839 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Type: Documentation

#838 Add support for `failure_issue_threshold` & `recovery_threshold`
  composer.json
  src/Sentry/Laravel/Features/ConsoleIntegration.php
Labels: Type: Improvement

#840 Always log SDK logs when verbose output is enabled
  src/Sentry/Laravel/Console/TestCommand.php
Labels: Type: Improvement

#833 Add span for publishing a job to the queue
  src/Sentry/Laravel/Features/QueueIntegration.php
Labels: Type: Improvement

#842 Improve `sentry:test` command
  src/Sentry/Laravel/Console/TestCommand.php
Labels: Type: Improvement

#841 Flush metrics when events are being flushed and after each request
  src/Sentry/Laravel/Http/FlushEventsMiddleware.php
  src/Sentry/Laravel/Integration.php
  src/Sentry/Laravel/ServiceProvider.php
Labels: Type: Improvement

#843 Bump PHP SDK to 4.5.0
  composer.json
Labels: Type: Improvement
