Repository getsentry/sentry-laravel, pull requests merged in 2024-07, with the labels that each got.

#914 Cache tracing
  config/sentry.php
  src/Sentry/Laravel/Features/CacheIntegration.php
  src/Sentry/Laravel/Features/Concerns/TracksPushedScopesAndSpans.php
  src/Sentry/Laravel/Features/Concerns/WorksWithSpans.php
  src/Sentry/Laravel/Features/HttpClientIntegration.php
  src/Sentry/Laravel/Features/LivewirePackageIntegration.php
  src/Sentry/Laravel/Features/NotificationsIntegration.php
  src/Sentry/Laravel/Features/QueueIntegration.php
  test/Sentry/Features/CacheIntegrationTest.php
Labels: Type: Improvement

#915 Prepare 4.7.0
  CHANGELOG.md
Labels: Type: Documentation

#918 Add Laravel version to bug template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: Type: Documentation

#920 Always remove XSRF-TOKEN cookie value before sending to Sentry
  src/Sentry/Laravel/Http/LaravelRequestFetcher.php
Labels: Type: Improvement

#921 Octane fixes
  src/Sentry/Laravel/Tracing/Middleware.php
  src/Sentry/Laravel/Tracing/Routing/TracingRoutingDispatcher.php
  src/Sentry/Laravel/Tracing/ServiceProvider.php
Labels: Type: Bug

#922 Lumen Context fix
  src/Sentry/Laravel/Integration/LaravelContextIntegration.php
Labels: Type: Bug

#923 Normalize array of key names before converting to string
  src/Sentry/Laravel/Features/CacheIntegration.php
  test/Sentry/Features/CacheIntegrationTest.php
Labels: Type: Bug

#925 Prepare 4.7.1
  CHANGELOG.md
Labels: Type: Documentation

#926 Improve stacktrace of test event
  src/Sentry/Laravel/Console/TestCommand.php
  src/Sentry/Laravel/ServiceProvider.php
Labels: Type: Improvement

#928 Fix publish command mangling .env file
  src/Sentry/Laravel/Console/PublishCommand.php
Labels: Type: Bug
