Repository getsentry/sentry-laravel, pull requests merged in 2024-03, with the labels that each got.

#859 Take all `http_*` options from the Laravel client in the test command
  src/Sentry/Laravel/Console/TestCommand.php
Labels: Type: Improvement

#845 Add support for Laravel 11
  .github/workflows/ci.yaml
  README.md
  composer.json
  config/sentry.php
  phpstan-baseline.neon
  phpunit.xml
  src/Sentry/Laravel/Integration.php
Labels: Type: Feature

#860 Prepare 4.3.0
  CHANGELOG.md
Labels: Type: Documentation

#865 Add missing functions to `FilesystemDecorator`
  phpstan-baseline.neon
  src/Sentry/Laravel/Features/Storage/FilesystemDecorator.php
Labels: Type: Bug

#864 Fix docs link
  README.md
Labels: Type: Documentation

#866 Prepare 4.3.1
  CHANGELOG.md
Labels: Type: Documentation

#867 Remove `"minimum-stability": "dev"`
  composer.json
Labels: Type: Improvement

#869 Add current Laravel context to event
  src/Sentry/Laravel/Integration/LaravelContextIntegration.php
  src/Sentry/Laravel/ServiceProvider.php
  test/Sentry/Integration/LaravelContextIntegrationTest.php
Labels: Type: Improvement
