Repository getsentry/sentry-laravel, pull requests merged in 2025-01, with the labels that each got.

#968 Add Scheduled Task Tracing
  src/Sentry/Laravel/Features/ConsoleSchedulingIntegration.php
  test/Sentry/Features/ConsoleSchedulingIntegrationTest.php
Labels: Type: Feature

#971 Prepare 4.11.0
  CHANGELOG.md
Labels: Type: Documentation

#974 Fix unable to parse string notifiable
  src/Sentry/Laravel/Features/NotificationsIntegration.php
Labels: Type: Bug
